#!/bin/sh

# /usr/bin/i3exit

case "$1" in
    lock)
        i3lock-fancy -f Comic-Sans-MS -- scrot -z
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        i3lock-fancy -f Comic-Sans-MS -- scrot -z & systemctl suspend
        ;;
    hibernate)
        i3lock-fancy -f Comic-Sans-MS -- scrot -z & systemctl hibernate
        ;;
    reboot)
        systemctl logind reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "== ! i3exit: missing or invalid argument ! =="
        echo "Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
        exit 2
esac

exit 0
