#!/usr/bin/python3

import time
import sys
import datetime
import os
import subprocess as s

def get_disk_space():
    disk_space = os.popen("df -h / | grep / | cut -d \" \" -f 9").read().strip()
    return "💾 " + disk_space

def get_time():
    months = ["January", "February", "March", "April", "May", "June", "July",
     "August", "September", "October", "November", "December"]

    format_time = " 📆 %d-%m-%Y | 🕟 %H:%M"
    return datetime.datetime.now().strftime(format_time)

def get_battery():
    power = os.popen("upower -i /org/freedesktop/UPower/devices/battery_BAT0").read().split()

    if power[power.index('state:') + 1] == 'charging':
        return "⚡" + power[power.index('percentage:') + 1]
    elif power[power.index('state:') + 1] == 'fully-charged':
        return "🔋 Full"
    else:
        return  "🔋" + power[power.index('percentage:') + 1]

def get_sound():
    return u"\U0001F50A" + " " + os.popen("amixer sget 'Master'").read().split()[20]

def write(data):
    sys.__stdout__.write('%s\n' % data)
    sys.__stdout__.flush()

def main():
    while True:
        data = ""
        data += get_time() + " | "
        data += get_battery() + " | "
        data += get_sound() + " | "
        data += get_disk_space() + " |  "
        write(data)
        time.sleep(1)

main()
