#!/bin/bash

# Script modified from:
# https://github.com/imlizardking57/dotfiles/blob/master/i3/scripts/volumecontrol.sh

case $1 in
  up)
    # set the volume on (if it was muted)
    amixer -D pulse set Master on > /dev/null
    # up the volume (+ 5%)
    amixer -D pulse sset Master 5%+ > /dev/null
    ;;
  down)
    amixer -D pulse set Master on > /dev/null
    amixer -D pulse sset Master 5%- > /dev/null
    ;;
  mute)
    # toggle mute
    amixer -D pulse set Master 1+ toggle > /dev/null
    ;;
  mic_mute)
      amixer set Capture toggle
    ;;
esac
