#!/bin/bash

find . -name "#*" -a -name "*#" -delete -print -or \
-name "*~" -delete -print -or \
-name "a.out" -delete -print -or \
-name "*.swp" -delete -print -or \
-name "*.o" -delete -print -or \
-name "vgcore*" -delete -print -or \
-name "*.gcno" -delete -print -or \
-name "*.gcda" -delete -print -or \
-name "libmy.a" -delete -print
