#!/bin/bash

if [ $# -eq 1 ] && [ $1 = "dark" ]; then
	feh --bg-scale ~/Pictures/wallpapers/MY_Wallpapers/black.png
	exit 0
fi

mapfile -t my_array < <( find ~/Pictures/wallpapers -type f )

function select_wallpaper_randomly()
{
    let a=${#my_array[@]}
    while [ true ]; do
        let index=$(( $RANDOM % a + 1 ))
        feh --bg-scale ${my_array[index]} 2> /dev/null
        if [ $? -eq 0 ]; then
            echo "This is : $(echo ${my_array[index]} | cut -d '/' '-f4-')"
            break
        fi
    done
}

if [ $# -eq 1 ] && [ $1 = "-i" ]; then
    while [ 1 ]; do
        select_wallpaper_randomly
        echo -ne "Next ? (y/n) : "
        read answer
        if [ $answer = "y" ]; then
            continue
        else
            exit 0
        fi
    done
else
    select_wallpaper_randomly
    exit 0
fi
